### ISSUE TITLE
Build error - Debian 7 64 bit

### ISSUE THREAD

**Issue by belovachap** [devcoin/core#1]
Running the command `make -f makefile.unix` on master causes the following output:

```
cshoop@debian:~/devcoin/src$ make -f makefile.unix USE_UPNP=
Building LevelDB ...
make[1]: Entering directory `/home/cshoop/devcoin/src/leveldb'
make[1]: *** No rule to make target `libleveldb.a'.  Stop.
make[1]: Leaving directory `/home/cshoop/devcoin/src/leveldb'
make: *** [leveldb/libleveldb.a] Error 2
```

**Comment by Satoshi0x** [comment]
I know this is closed but isn't there something about Debian 7 as well as leveldb that caused the blockchain fork when bitcoind v0.7 (using BDB 4.8) were rejecting a block that miners using v0.8 (ldb) accepted with too many txns for BDB 4.8 to have "locks" for (10,000 limit)? Then the whole fiasco where devs had to influence all the v0.8 bitcoind miner pools (70% of the miners at the time) to mine the other forked chain that v0.7 rejected until they converged at a block both accepted before making every pool upgrade to v0.8 bitcoind (and ldb) for good? 

Consensus by intervention. Are we looking at similar fragmentation problems with Devcoin to fix at a later date to recover our value that may have happened similar in the way the blockchain fork that I described above (disclosed a day later btw to the public)? And if so, I feel like we're getting closer.
