### ISSUE TITLE
Devcoin Core 22.x for Windows (private-alpha) Stuck on Dec 21, 2022 for 7 days

### ISSUE THREAD

**Issue by Satoshi0x** [devcoin/core#107]
![image](https://user-images.githubusercontent.com/48847567/209910338-cc3c4cd7-30a0-4c1a-a334-4188952a5e63.png)

Tried to reindex and got to the same block where I am stuck as you can see here. It shows how many blocks behind I am. Any suggestions? Maybe add specific peers to Devcoin.conf? Would love to catch up.

Unsure what happened! I doubt its the operating system and build causing problem I've had ZERO issues with the Windows priv-alpha from @develCuy since receiving the file early 2022.

**Comment by develCuy** [comment]
Things are working as designed. Please refer to #73
