### ISSUE TITLE
test_devcoin, tests failing

### ISSUE THREAD

**Issue by belovachap** [devcoin/core#11]
There appear to be legitimate test failures if you run test_devcoin. Devcoin modified the Bitcoin source in a few places without updating the expectations described in the automated tests. This ticket is for going in, understanding why the tests are failing and updating them to describe Devcoin expectations.

**Comment by ctya** [comment]
I am marking old items that can be closed.  We will re-open with more recent issues since this 1 year old or more.  Please close this issue

**Comment by belovachap** [comment]
Closing b/c old :) :+1:
