### ISSUE TITLE
Do we need README.txt?

### ISSUE THREAD

**Issue by belovachap** [devcoin/core#12]
Why is there a README.txt and a README.md? Seems like the .txt should be absorbed into various doc/ documents or the markdown file.

Ticket is for figuring out if there's any useful info in README.txt, moving it to better homes, and deleting it.

**Comment by ctya** [comment]
I am marking old items that can be closed.  We will re-open with more recent issues since this 1 year old or more.  Please close this issue

**Comment by belovachap** [comment]
Closing b/c old :) :+1:
