### ISSUE TITLE
Name of binaries (Devoind, devcoind, Devcoin-qt, devcoin-qt, Devcoin-Qt)?

### ISSUE THREAD

**Issue by belovachap** [devcoin/core#14]
There's some variation on the capitalization of the binaries we produce last I checked. This might have been addressed in sidhujag's latest stuff but my vote would be to standardize on lower casing (e.g. "devcoind" and "devcoin-qt"). Open to other ideas, just looking for some consistency :)

**Comment by ctya** [comment]
close b/c old plz
