### ISSUE TITLE
Debian Upgrade Path

### ISSUE THREAD

**Issue by belovachap** [devcoin/core#17]
It struck me this morning that it would be pretty poor form to release a backward incompatible version of the client without some idea of how to handle all the existing Devcoin client users.

We need to document on the devtome how we think the user upgrade experience should go. Even if it's literally: "Install new client in non-conflicting manner (e.g. change the data-dir temporarily), copy wallet address, close client. Open old client, send all your devcoins to new wallet address, close old wallet. Clean up .devcoin folder mess. Success!"

But I hope it's easier than that :)

**Comment by ctya** [comment]
close b/c old plz
