### ISSUE TITLE
Devcoin based version numbers

### ISSUE THREAD

**Issue by belovachap** [devcoin/core#2]
I don't think it makes sense to be using the Bitcion wallet version number if we're going to maintain this project. I'd propose making our next client release 1.0.0 and go from there.

This ticket would require us to update the version number in the client to read out something like 1.0.0rc1-hashasdf

**Comment by ctya** [comment]
I am marking old items that can be closed. We will re-open with more recent issues since this 1 year old or more. Please update as "closed b/c old" and close the issue

**Comment by belovachap** [comment]
"closed b/c old"
