### ISSUE TITLE
Apple, Ubuntu, MS app stores?

### ISSUE THREAD

**Issue by belovachap** [devcoin/core#20]
This isn't really fleshed out but I wanted to get a stub of a ticket going. Namecoin has enjoyed a recent resurgence in dev activity and it looks like they're shooting for Apple App Store inclusion https://github.com/namecoin/namecoin/issues/132

Although I am of the mindset that people should be looking over and talking about the code that holds our community together, it's just not realistic to expect that everyone wants to/needs to participate at that level. They should be off deving whatever it is that matters to them and leaving the computer work to those that aspire to take on that challenge.

Any way, I will probably come back later and split this into more actionable chunks. I don't think this is required for 1.0.0. But it could make the cut for the dev schedule immediately after.

**Comment by ctya** [comment]
I am marking old items that can be closed.  We will re-open with more recent issues since this 1 year old or more.  Please close this issue

**Comment by belovachap** [comment]
Closing b/c old :) :+1:
