### ISSUE TITLE
Do you want to make a testnet? It has to be a testnet.

### ISSUE THREAD

**Issue by belovachap** [devcoin/core#24]
It sounds like we don't have much of a testnet (see dev forum and checkpoints.cpp comments). I think we'll appreciate having one in the long-run because it gives developers (core team and otherwise) a place to try out new software, hardware, applications, ideas etc. And it's possible to successfully mine with drastically less hash power since testnet tokens are way less valuable than prodnet devcoins ;)

More actionable tickets to come as folks figure out what is needed :)

**Comment by ctya** [comment]
New testnet information

Testnet Block Explorer
https://testnet.devcoin.cloud

addnode=testnet.devcoin.cloud
addnode=phoenix.devcoinresource.com

**Comment by belovachap** [comment]
Neat! Looks like a testnet :)
