### ISSUE TITLE
Not compiling on Debian 6 and Ubuntu 10

### ISSUE THREAD

**Issue by DevElCuy** [devcoin/core#26]

**Comment by ctya** [comment]
I was able to compile on Ubuntu 16
`
sudo aptitude -y update && sudo aptitude -y safe-upgrade
sudo aptitude -y install build-essential python-software-properties autoconf libtool libssl-dev libboost-all-dev libdb4.8-dev libdb4.8++-dev
sudo aptitude -y add-apt-repository ppa:bitcoin/bitcoin
sudo aptitude -y install bitcoin
sudo aptitude -y build-dep bitcoin
cd core/src
make -f makefile.unix USE_UPNP=-
cd ../
qmake USE_UPNP=0 USE_DBUS=1 USE_QRCODE=1
make
`
