### ISSUE TITLE
warning: ‘globalDownloadIndex’ defined but not used

### ISSUE THREAD

**Issue by belovachap** [devcoin/core#27]
Ticket is for researching and, I hope, deleting this globalDownloadIndex variable that the compiler keeps telling me that we don't use:

```
In file included from main.cpp:18:0:
receiver.h: At global scope:
receiver.h:12:12: warning: ‘globalDownloadIndex’ defined but not used [-Wunused-variable]
 static int globalDownloadIndex = 10;
```

**Comment by ctya** [comment]
This PR fixes this issue
https://github.com/devcoin/core/pull/47
