### ISSUE TITLE
Update peers list

### ISSUE THREAD

**Issue by belovachap** [devcoin/core#28]
Not sure what this entails but people on the #devcoin irc have noticed that it takes a long time for the client to find nodes initially. There's a good chance that the peers list we ship is outdated so here's a ticket to update that list.

**Comment by ctya** [comment]
https://github.com/devcoin/core/pull/37

**Comment by belovachap** [comment]
Neat... very kind of you to work on these tickets... are people using this client? I feel like the people working on the project grew weary and wandered off. Maybe there are still things going on?

Any who, I dug around on some of my backup drives and found a file that might be my old devcoin wallet. I think there was a bounty for getting the 1.0.0 client together that I was offering on the forum we used to talk on. If I can get this to compile and I still have access to some devcoins, perhaps I can send you (and @develCuy) some for the effort.

**Comment by ctya** [comment]
Hey sorry I missed this communication from months ago.

DVC is going through a bit of a renewal with some integrations with other projects.  It definitely has some more interest this year.

You can communicate with us at the bitcointalk forum
https://bitcointalk.org/index.php?topic=233997.7600

**Comment by belovachap** [comment]
Nice! I wasn't able to make much progress myself and am off fiddling with other projects :( Glad people are working on it again, though :) Hope it catches on :globe_with_meridians:

**Comment by ctya** [comment]
This can be closed.  Thank you

**Comment by belovachap** [comment]
:rocket:
