### ISSUE TITLE
Cool QT

### ISSUE THREAD

**Issue by Smeagol-Gollum** [devcoin/core#31]
Making an aesthetically pleasing qt may help speed up user adoption.  (Megacoin-qt is a good example)

https://ip.bitcointalk.org/?u=http%3A%2F%2Fi1367.photobucket.com%2Falbums%2Fr783%2Fmegacoin%2Fnewclient2_zpsf6457f75.jpg&t=542&c=k6TSa05WP9gpLQ

**Comment by ctya** [comment]
I am marking old items that can be closed.  We will re-open with more recent issues since this 1 year old or more.  Please close this issue

**Comment by ctya** [comment]
close b/c old plz
