### ISSUE TITLE
Receiver files cannot be hosted on sites with SSL

### ISSUE THREAD

**Issue by ctya** [devcoin/core#36]
Receiver files cannot be hosted on sites with SSL

This receiver host is broken as a result
https://raw.githubusercontent.com/wiser-/Devtome/master/receiver.csv

**Comment by develCuy** [comment]
@ctya, now that #44 is fixed, what happens this?

**Comment by ctya** [comment]
There are only three receiver hosts listed in receivers.h (we need more there, off topic)
I opened separate issues for each of those hosts b/c none of them have a valid SSL configuration.

Meanwhile I will try to test with my own hosts to debug the issue. 

If you can get these three receiver host configurations corrected, it will be very helpful.
Maybe a minimum requirement for hosting anything should be a valid SSL configuration.

**Comment by ctya** [comment]
Tested and looks like we just needed to have SSL enabled in the make file.  Works well once this is changed.  Here is the PR to fix it
https://github.com/devcoin/core/pull/60ZQblM8Jlq8e7vB2pIf

**Comment by ctya** [comment]
Fixed with other Pull Requests
