### ISSUE TITLE
Compile Error because of deprecated BIGNUM in openssl 1.1.0g

### ISSUE THREAD

**Issue by ctya** [devcoin/core#44]
BigNum is deprecated.
With openssl 1.1.0 g compiling fails.
Openssl versions prior to 1.1.0 f were working well, but now these errors stop the compiler on Linux

bignum.h:51:24: error: invalid use of incomplete type ‘BIGNUM {aka struct bignum_st}’
 class CBigNum : public BIGNUM
                        ^~~~~~
In file included from /usr/include/openssl/crypto.h:31:0,
                 from allocators.h:12,
                 from crypter.h:7,
                 from keystore.h:8,
                 from script.h:14,
                 from auxpow.cpp:4:
/usr/include/openssl/ossl_typ.h:80:16: note: forward declaration of ‘BIGNUM {aka struct bignum_st}’
 typedef struct bignum_st BIGNUM;
                ^~~~~~~~~
In file included from script.h:15:0,
                 from auxpow.cpp:4:
bignum.h: In constructor ‘CBigNum::CBigNum()’:
bignum.h:56:9: error: ‘BN_init’ was not declared in this scope
         BN_init(this);
         ^~~~~~~
bignum.h:56:9: note: suggested alternative: ‘BN_print’
         BN_init(this);
         ^~~~~~~
         BN_print
bignum.h: In copy constructor ‘CBigNum::CBigNum(const CBigNum&)’:
bignum.h:61:9: error: ‘BN_init’ was not declared in this scope
         BN_init(this);
         ^~~~~~~

**Comment by ctya** [comment]
I finally have this corrected and running test builds now.  Other coins had similar issues with old code and new versions of openssl.  The namespace was also problematic.  After a few days of working on it, I think I found the last issue and builds are working again.  Commit coming soon

**Comment by develCuy** [comment]
@ctya can you provide links to the patches/commits from those other coins?

**Comment by develCuy** [comment]
@ctya I looks like this fixes #36, can you confirm?

**Comment by develCuy** [comment]
@ctya used this for current PR: https://github.com/peercoin/peercoin/pull/153/commits/5b09830e5de0f5105534e69dbf4acffb3255869b
