### ISSUE TITLE
OSX build fails on serialize.h duplicate class member

### ISSUE THREAD

**Issue by ctya** [devcoin/core#51]
serialize.h:910:10 error: class member cannot be redeclared
....
serialize.h:898:10  previous declaration is here

OSX compile stops

**Comment by ctya** [comment]
https://github.com/lokkju/primecoin/commit/e71d317a5ba9b587f6f37c8e2f34458ae486dd65serialize.h:827:10: error: cserialize.h:827:10: error: class member cannot be redeclaredlass member cannot be redeclared

and


https://github.com/metrocoins/metrocoin/issues/1

**Comment by develCuy** [comment]
Ok, now I see, the fix makes a lot of sense!
