### ISSUE TITLE
Document the Bitcoin source code version in master branch

### ISSUE THREAD

**Issue by develCuy** [devcoin/core#53]
@belovachap @sidhujag, do you guys know what is the actual Bitcoin version used in current master branch?
@ctya since you updated the README file, can you include the this info?

Reason: Get ready for a major version update, old code is no safe

**Comment by belovachap** [comment]
I don't know the answer for sure, but looking at some of the files makes me think the code base came from https://github.com/domob1812/i0coin/releases/tag/i0coin-0.8.5-1

**Comment by develCuy** [comment]
Since we are forking straight from Bitcoin Core 22.x (check #73), this issue has been solved already
