### ISSUE TITLE
Add current round to getinfo command

### ISSUE THREAD

**Issue by develCuy** [devcoin/core#65]
This is current output:

```
$ devcoind getinfo
{   
    "version" : 80602,
    "protocolversion" : 69901,
    "walletversion" : 20300,
    "balance" : 0.00000000,
    "blocks" : 341427,
    "timeoffset" : 0,
    "connections" : 1,
    "proxy" : "",
    "difficulty" : 839437720922.89233398,
    "testnet" : false,
    "keypoololdest" : 1304970400,
    "keypoolsize" : 100,
    "paytxfee" : 0.00000000,
    "errors" : ""
}
```

This is what I want:

```
$ devcoind getinfo
{   
    "version" : 80602,
    "protocolversion" : 69901,
    "walletversion" : 20300,
    "balance" : 0.00000000,
    "blocks" : 341427,
    "timeoffset" : 0,
    "connections" : 1,
    "proxy" : "",
    "difficulty" : 839437720922.89233398,
    "testnet" : false,
    "keypoololdest" : 1304970400,
    "keypoolsize" : 100,
    "paytxfee" : 0.00000000,
    "errors" : "",
    "round" : 85
}
```

Reason: Have an easy quick way to read the current round.

**Comment by ctya** [comment]
http://www.devtome.com/doku.php?id=devtome_stats&s[]=current&s[]=round
"The earnings are calculated at increments of 4000 blocks, minus lead time of 2700 blocks. The payout blocks start at rounds in increments of 4,000.
Round 36 goes from block 137,300 to 141,300, and starts paying out at block 144,000.
Round 37 goes from block 141,300 to 145,300, and starts paying out at block 148,000."

Putting this here so incoming code changes follow the documentation

**Comment by ctya** [comment]
Ready
https://github.com/devcoin/core/pull/66

**Comment by develCuy** [comment]
Code merged, let's keep this moving!
