### ISSUE TITLE
Compiler warning Comparison between signed and unsigned - Bounty: 1M DVC

### ISSUE THREAD

**Issue by ghost** [devcoin/core#70]
In file included from ./util/arena.h:10:0,
                 from ./db/skiplist.h:30,
                 from ./db/memtable.h:11,
                 from db/memtable.cc:5:
db/memtable.cc: In member function ‘void leveldb::MemTable::Add(leveldb::SequenceNumber, leveldb::ValueType, const leveldb::Slice&, const leveldb::Slice&)’:
db/memtable.cc:104:31: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   assert((p + val_size) - buf == encoded_len);
          ~~~~~~~~~~~~~~~~~~~~~^~~~


ALSO


util/bloom.cc: In member function ‘virtual void leveldb::{anonymous}::BloomFilterPolicy::CreateFilter(const leveldb::Slice*, int, std::__cxx11::string*) const’:
util/bloom.cc:50:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (size_t i = 0; i < n; i++) {
                        ~~^~~

ALSO

util/logging.cc: In function ‘bool leveldb::ConsumeDecimalNumber(leveldb::Slice*, uint64_t*)’:
util/logging.cc:67:40: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
           (v == kMaxUint64/10 && delta > kMaxUint64%10)) {
                                  ~~~~~~^~~~~~~~~~~~~~~

**Comment by develCuy** [comment]
We have got a fair amount of alerts regarding signed vs. unsigned comparisons, so we basically have to do a lot of small edits and test everything again. It is important to have a clean compilation, for that reason I set a bounty of 1M DVC from the DevFund to be distributed among all the people that work to fix this issue. The tester assigned is @cpsilent (Qtera), which should certify the fix

**Comment by develCuy** [comment]
Work on #73 changed the game! Bitcoin Core 22.0.0 codebase compiles quite clean! This ticket is not a problem anymore
