### ISSUE TITLE
Compiling issues under Ubuntu 16.04

### ISSUE THREAD

**Issue by novacadian** [devcoin/core#72]
Experience with Ubuntu 16.04

Downloaded core-f29c33c44e003d02ad2d5e3aff73e923229f52f0.

There was an error surrounding permissions. My assumption was ownership which lost some time. It ended up being the build_detect_platform shell script, which required a "chmod +x build_detect_platform" on it for the qmake and make instructions.

Now having issues with libcurl. "locate curl.h" returns "/usr/include/curl/curl.h". Yet getting the following error:

g++: error: /home/nova/Downloads/core-f29c33c44e003d02ad2d5e3aff73e923229f52f0/src/curl/lib/.libs/libcurl.a: No such file or directory
Makefile:516: recipe for target 'devcoin-qt' failed
make: *** [devcoin-qt] Error 1

Will look into it further a little later.

**Comment by ctya** [comment]
Hi Nova, thanks for the feedback.
Can you try the latest Master branch and let me know the results?
chmod +x build_detect_platform was added already and the curl updates happened around the same time so I am hoping we fixed this already.

If you still have trouble, feel free to post then entire output here and I'll duplicated it in my test rig.

**Comment by novacadian** [comment]
Issues resolved by following cpol's wonderful guide, who's link is included below.

https://steemit.com/busy/@cpol/how-to-compile-your-very-own-devcoin-wallet-in-ubuntu-18-04
