### ISSUE TITLE
% synced progress bar is wrong

### ISSUE THREAD

**Issue by belovachap** [devcoin/core#9]
devcoin-qt knows how many weeks behind it is while syncing but does not accurately reflect it in the progress bar.
![progress_bar_bug](https://cloud.githubusercontent.com/assets/396781/3489836/1e1f5f02-0549-11e4-97ef-d3d8a08c7d16.png)

**Comment by ctya** [comment]
This is fixed

**Comment by belovachap** [comment]
I'll believe it :+1:
