### ISSUE TITLE
Transfer Reddit Moderator

### ISSUE THREAD

**Issue by belovachap** [devcoin/core#91]
Hi there, I don't pay much attention to the project these days and have been asked to swap out as reddit moderator.

They said to tell you it's Dan if that helps. If it's legit I'm happy to give the reins over to someone with eyes on the project :)

**Comment by satoshi0x** [comment]
I asked for this privilege. Had no idea it was you @belovachap - I have studied your contributions in these branches and I am very very honored to speak with you. Don't be a stranger here - but I would love to take Reddit mod privs over and dress the place up a bit.

**Comment by belovachap** [comment]
@satoshi0x I added you as a moderator. I'll drop off once we hear back from @develCuy.

**Comment by develCuy** [comment]
Thank you @belovachap! @satoshi0x is Devcoin's Marketing guy so you did the right choice. Thank you!!

**Comment by belovachap** [comment]
Transfer complete! 🚀
