### ISSUE TITLE
Segwit

### ISSUE THREAD

**Issue by develCuy** [devcoin/core#92]
¿Should we allow Segwit format addresses in the new Devcoin 22.0.0?

**Comment by satoshi0x** [comment]
> ¿Should we allow Segwit format addresses in the new Devcoin 22.0.0?

I have no technical basis for this but sure? Why not.

**Comment by develCuy** [comment]
Thanks for your feedback @satoshi0x! Let's make Segwit happen: #93

**Comment by satoshi0x** [comment]
Yes. It will enable lightning payments and other goodies.

Daniel R. Treccia
***@***.***
keybase.io/satoshi0x
