### ISSUE TITLE
Alert Key Compromised message in v0.8.9.0 beta for Windows.

### ISSUE THREAD

**Issue by satoshi0x** [devcoin/core#94]
2022-01-31 2:53 PM CST: The "final alert" message "URGENT: Alert key compromised, upgrade required" is showing in my Devcoin-Qt client.

RPC for 'getinfo' shows the message, this is something I've never seen in Devcoin. Wondering why its showing up now?

Code:
{
"version" : 80900,
"protocolversion" : 70001,
"walletversion" : 60000,
"balance" : *********,
"blocks" : 502474,
"timeoffset" : 0,
"connections" : 3,
"proxy" : "",
"difficulty" : 28502782.90499028,
"testnet" : false,
"keypoololdest" : 1630823224,
"keypoolsize" : 101,
"paytxfee" : 0.00000000,
"unlocked_until" : 0,
"errors" : "URGENT: Alert key compromised, upgrade required",
"round" : 125

Found info that seemingly describes this message being made by Bitcoin Core devs on a mailing list message from Bryan Bishop (I remember this from Jul 2018):

https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2018-July/016189.html

Why is this going on? markm? develcuy - thoughts?

**Comment by develCuy** [comment]
This is a very old known bug, all we have to do is ignore it till we can safely upgrade to 22.x
